# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\drink_progress.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_drinkProgress(object):
    def setupUi(self, drinkProgress):
        drinkProgress.setObjectName("drinkProgress")
        drinkProgress.resize(405, 97)
        self.progressBar = QtWidgets.QProgressBar(drinkProgress)
        self.progressBar.setGeometry(QtCore.QRect(20, 20, 371, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(drinkProgress)
        self.label.setGeometry(QtCore.QRect(20, 70, 47, 13))
        self.label.setObjectName("label")

        self.retranslateUi(drinkProgress)
        QtCore.QMetaObject.connectSlotsByName(drinkProgress)

    def retranslateUi(self, drinkProgress):
        _translate = QtCore.QCoreApplication.translate
        drinkProgress.setWindowTitle(_translate("drinkProgress", "Form"))
        self.label.setText(_translate("drinkProgress", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    drinkProgress = QtWidgets.QWidget()
    ui = Ui_drinkProgress()
    ui.setupUi(drinkProgress)
    drinkProgress.show()
    sys.exit(app.exec_())
